[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Catalyst = "15.0.8"
ComponentArrays = "0.15.30"
DiffEqCallbacks = "4.10.1"
DiffEqNoiseProcess = "5.24.1"
DiffEqParamEstim = "2.2.0"
ForwardDiff = "0.10.39"
Groebner = "0.10.0"
HomotopyContinuation = "2.15.2"
JumpProcesses = "9.18.0"
Latexify = "0.16.10"
LsqFit = "0.15.1"
ModelingToolkit = "9.83.0"
NaNMath = "1.1.3"
NonlinearSolve = "4.10.0"
Optim = "1.13.2"
Optimization = "4.8.0"
OptimizationOptimJL = "0.4.5"
OrdinaryDiffEq = "6.101.0"
Plots = "1.41.1"
SimpleUnPack = "1.1.0"
SteadyStateDiffEq = "2.6.0"
StochasticDiffEq = "6.81.0"
Symbolics = "6.57.0"
