# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: ../_site

# https://quarto.org/docs/websites/
website:
  title: Quarto Julia Template
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/sosiristseng/jl-diffeq
  site-url: https://sosiristseng.github.io/jl-diffeq
  sidebar:
    style: docked
    search: true
    contents:
      - index.ipynb
      - section: "ODE"
        contents: ode/*.ipynb
      - section: "Stochastic"
        contents: stochastic/*.ipynb
      - section: "Advanced"
        contents: advanced/*.ipynb
      - section: "Models"
        contents: models/*.ipynb
      - section: "Tips"
        contents: tips/*.ipynb
    tools:
      - icon: github
        href: https://github.com/sosiristseng/jl-diffeq

# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly
    # css: styles.css

# Default options
# notebook-links: true

# Execution
# execute:
#   cache: true
# engines: ['julia']
